config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'questions/index'
    get 'questions/show'
  end
  get 'questions/index'
  get 'questions/show'
  namespace :admins do

  end
  namespace :admins do
    get "/top" => "homes#top", as: "top"

    resources :articles
    resources :categories, only:[:index, :create, :edit, :update]
    resources :users, only:[:index, :show, :update]
    resources :post_articles, only:[:index,:create, :show, :destroy]
    resources :questions, only:[:index, :create, :edit, :update]
    resources :results, only:[:index, :new, :create, :show, :edit, :update]
  end

    devise_for :admins, controllers: {
      sessions: 'admins/sessions'
    }


  scope module: :public do
    devise_for :users

    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :articles, only:[:index, :show]
    resources :users, only:[:show, :edit, :update] do
      resource :relationships, only:[:create, :destroy]
       get 'followings' => 'relationships#followings', as: 'followings'
       get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get :resign
        patch :withdraw
      end
    end
    resources :post_articles, only:[:index, :create, :show, :destroy] do
      resource :favorites, only:[:create, :destroy ]
      resources :post_comments, only:[:create, :destroy]
    end
    resources :questions, only:[:show, :update] do
      collection do
        get :start
        get :goal_1
        get :goal_2
      end
    end
    resources :results, only:[:index, :show]

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
  belongs_to :category
  
  attachment :image
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :articles
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_article
end

app/models/post_article.rb
class PostArticle < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

  attachment :image

  validates :body, presence: true, length: { minimum: 3 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_article
  
  validates :comment, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_articles, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  attachment :profile_image

  validates :name,
      uniqueness: true, length: { in: 2..20 }
  validates :introduction,
      length: { maximum: 100 }

 def follow(user_id)
    relationships.find_or_create_by(followed_id: user_id)
 end
 def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
 end
 def following?(user)
    followings.include?(user)
 end

 def active_for_authentication?
    super && (self.is_active == true)
 end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  
  def top
    @articles = Article.all
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_articles = @user.post_articles.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    
    redirect_to admins_users_path(@user)
  end
  
  private
  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile_image])
   end
end

app/helpers/admins/articles_helper.rb
module Admins::ArticlesHelper
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/post_articles_helper.rb
module Admins::PostArticlesHelper
end

app/helpers/admins/questions_helper.rb
module Admins::QuestionsHelper
end

app/helpers/admins/results_helper.rb
module Admins::ResultsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/homes/top.html.erb
<div class="container px-5">
    <div class="row mt-3">
        <div class="mx-auto text-center">
            <h2>CoffeeBeats AdminsPage</h2>
        </div>
    </div>

    <div class="row mt-5">
        <div class="link-btn px-5">
            <%= link_to "記事を追加", new_admins_article_path, class:"btn btn-primary ml-5" %>
            <%= link_to "カテゴリー一覧", admins_categories_path, class: "btn btn-info ml-3" %>
        </div>
        <div class="article-table col-md-10 mt-3 mx-auto">
            <table class="table">
                <thead>
                    <tr class="table-active">
                        <th>ID</th>
                        <th>Title</th>
                        <th colspan="2"></th>
                        <th>Created</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <% @articles.each_with_index do |article, i| %>
                            <td><%= i + 1 %></td>
                            <td>
                                <%= link_to admins_article_path(article.id) do %>
                                <%= article.title %>
                                <% end %>
                            </td>
                            <td colspan="2"></td>
                            <td><%= article.created_at.strftime("%Y/%m/%d") %></td>

                            <td>
                                <%= link_to "編集", edit_admins_article_path(article.id), class:"btn btn-success" %>
                            </td>
                            <td>
                                <%= link_to "削除", admins_article_path(article.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class:"btn btn-danger" %>
                            </td>
                    </tr>
                        <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>