config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'questions/index'
    get 'questions/show'
  end
  get 'questions/index'
  get 'questions/show'
  namespace :admins do

  end
  namespace :admins do
    get "/top" => "homes#top", as: "top"

    resources :articles
    resources :categories, only:[:index, :create, :edit, :update]
    resources :users, only:[:index, :show, :update]
    resources :post_articles, only:[:index,:create, :show, :destroy]
    resources :questions, only:[:index, :create, :edit, :update]
    resources :results, only:[:index, :new, :create, :show, :edit, :update]
  end

    devise_for :admins, controllers: {
      sessions: 'admins/sessions'
    }


  scope module: :public do
    devise_for :users

    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :articles, only:[:index, :show]
    resources :users, only:[:show, :edit, :update] do
      resource :relationships, only:[:create, :destroy]
       get 'followings' => 'relationships#followings', as: 'followings'
       get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get :resign
        patch :withdraw
      end
    end
    resources :post_articles, only:[:index, :create, :show, :destroy] do
      resource :favorites, only:[:create, :destroy ]
      resources :post_comments, only:[:create, :destroy]
    end
    resources :questions, only:[:show, :update] do
      collection do
        get :start
        get :goal_1
        get :goal_2
      end
    end
    resources :results, only:[:index, :show]

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
  belongs_to :category
  
  attachment :image
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :articles
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_article
end

app/models/post_article.rb
class PostArticle < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

  attachment :image

  validates :body, presence: true, length: { minimum: 3 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_article
  
  validates :comment, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_articles, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  attachment :profile_image

  validates :name,
      uniqueness: true, length: { in: 2..20 }
  validates :introduction,
      length: { maximum: 100 }

 def follow(user_id)
    relationships.find_or_create_by(followed_id: user_id)
 end
 def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
 end
 def following?(user)
    followings.include?(user)
 end

 def active_for_authentication?
    super && (self.is_active == true)
 end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  
  def top
    @articles = Article.all
  end
end

app/controllers/admins/results_controller.rb
class Admins::ResultsController < ApplicationController

  def index
    @results = Result.all
  end

  def new
    @result = Result.new
  end

  def create
    @result = Result.new(result_params)
    @result.save

    redirect_to admins_results_path
  end

  def show
    @result = Result.find(params[:id])
  end

  def edit
    @result = Result.find(params[:id])
  end

  def update
    @result = Result.find(params[:id])
    @result.update(result_params)
    
    redirect_to admins_result_path(@result)
  end

  private
    def result_params
      params.require(:result).permit(:result_type, :type_detail, :country)
    end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post_articles = @user.post_articles.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    
    redirect_to admins_users_path(@user)
  end
  
  private
  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile_image])
   end
end

app/helpers/admins/articles_helper.rb
module Admins::ArticlesHelper
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/post_articles_helper.rb
module Admins::PostArticlesHelper
end

app/helpers/admins/questions_helper.rb
module Admins::QuestionsHelper
end

app/helpers/admins/results_helper.rb
module Admins::ResultsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/results/edit.html.erb
<div class="container">

  <div class="row">
    <div class="new-results">
      <%= form_with model: @result, url: admins_result_path(@result.id), local:true do |f| %>
        <div class="form-group">
          <%= f.label :result_type, "タイプ" %>
          <%= f.text_field :result_type, class:"form-control ml-3" %>
        </div>
        <div class="form-group">
          <%= f.label :type_detail, "タイプ詳細" %>
          <%= f.text_area :type_detail, class:"form-control ml-3", size: "55x10" %>
        </div>
        <div class="form-group">
          <%= f.label :country, "代表国" %>
          <%= f.text_field :country, class:"form-control ml-3" %>
        </div>
        <div class="action">
          <%= f.submit "更新", class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/results/index.html.erb
<div class="container sm-12 md-8 lg-5 px-5 px-sm-0">

  <div class="row mt-5">
    <h4>診断結果一覧</h4>
    <%= link_to "新規登録", new_admins_result_path, class:"btn btn-primary ml-3" %>
  </div>

  <div class="row mt-3">
    <dvi class="results-box col-md-6">
      <table class="table">
        <thead>
          <tr class="table-active">
              <th>ID</th>
              <th>Type</th>
              <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @results.each do |result| %>
            <td><%= result.id %></td>
            <td><%= result.result_type %></td>
            <td><%= link_to "詳細", admins_result_path(result.id), class:"btn btn-info" %></td>
          </tr>
            <% end %>
        </tbody>
      </table>
    </dvi>
  </div>

</div>

app/views/admins/results/new.html.erb
<div class="container">

  <div class="row mt-5">
    <div class="new-results">
      <%= form_with model: @result, url: admins_results_path, local:true do |f| %>
        <div class="form-group">
          <%= f.label :result_type, "タイプ" %>
          <%= f.text_field :result_type, class:"form-control ml-3" %>
        </div>
        <div class="form-group">
          <%= f.label :type_detail, "説明文" %>
          <%= f.text_area :type_detail, class:"form-control ml-3", size: "55x10" %>
        </div>
        <div class="form-group">
          <%= f.label :country, "代表国" %>
          <%= f.text_field :country, class:"form-control ml-3" %>
        </div>
        <div class="action">
          <%= f.submit "登録", class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/results/show.html.erb
<div class="container sm-12 md-8 lg-5 px-5 px-sm-0">

  <div class="row mt-5">
    <h4>タイプ詳細</h4>
  </div>

  <div class="row mt-3">
    <h4><strong><%= @result.result_type %></strong></h4>
  </div>

  <div class="row mt-3">
    <div class="text-box col-md-8 border p-3">
      <%= @result.type_detail %>
    </div>
  </div>

  <div class="row mt-3">
    <p>代表国：<%= @result.country %></p>
  </div>

  <div class="link-btn mt-5">
    <%= link_to "一覧に戻る", admins_results_path, class:"btn btn-info" %>
    <%= link_to "編集", edit_admins_result_path(@result.id), class:"btn btn-success" %>
  </div>
</div>

app/views/admins/users/index.html.erb
<div class="container sm-12 md-8 lg-5 px-5 px-sm-0">

  <div class="row mt-5">
    <h4>ユーザー一覧</h4>
  </div>

  <div class="row mt-3">
    <div class="users-table col-md-8 mx-auto">
      <table class="table">
        <thead>
          <tr class="table-active">
            <th>ID</th>
            <th>Name</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @users.each do |user| %>
                <td width="100"><%= user.id %></td>
                <td>
                  <%= link_to admins_user_path(user.id) do %>
                    <%= user.name %>
                  <% end %>
                </td>
              <% if user.is_active == true %>
                <td class="text-success">有効</td>
              <% else %>
                <td>退会</td>
              <% end %>
          </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/admins/users/show.html.erb
<div class="container sm-12 md-8 lg-5 px-5 px-sm-0">

  <div class="row mt-3">
    <div class="col-md-4">
      <div class="row">
        <h4><strong><%= @user.name %></strong>の会員情報</h4>
      </div>
      <div class="row">
        <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, fallback:"no_image.jpg", class:"mx-auto" %>
      </div>
      <div class="row mt-3">
        <%= link_to "一覧にもどる", admins_users_path, class:"btn btn-info mx-auto" %>
      </div>
    </div>

    <div class-"col-md-6 offset-2">
      <table class="table mt-5">
        <tbody>
          <tr>
            <th>名前</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
              <th>メールアドレス</th>
              <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>自己紹介</th>
            <td><%= @user.introduction %></td>
          </tr>
          <tr>
              <th>ステータス</th>
              <% if @user.is_active == true %>
              <td class="text-success">有効</td>
              <% else %>
              <td>退会</td>
              <% end %>
          </tr>
          <tr>
            <th>ステータス切替</th>
            <td>
              <%= form_with model: @user, url: admins_user_path(@user.id), local:true do |f| %>
                <%= f.radio_button :is_active, :true %>
                <%= f.label :is_active_true, "有効" %>
                <%= f.radio_button :is_active, :false, class:"ml-3" %>
                <%= f.label :is_active_false, "退会" %>
                <%= f.submit "編集", class:"btn btn-success ml-3" %>
            </td>
              <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row mt-3">
    <h4><%= @user.name %>の投稿一覧</h4>
  </div>
  <div class="row mt-3">
    <% @post_articles.each do |post_article| %>
      <div class="post_article-box col-md-8 mt-3 ml-auto shadow-sm">
        <% user = User.find(post_article.user_id) %>
        <%= link_to post_article_path(post_article.id, name:user.name) do %>
          <table class="table">
            <tbody>
              <tr>
                <td width="75">
                  <%= attachment_image_tag post_article.user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg" %><br />
                  <%= post_article.user.name %>
                </td>
                <td width="550">
                  <%= post_article.body.truncate(24) %>
                </td>
                <td></td>
                <td>
                  <%= attachment_image_tag post_article, :image, :fill, 200,150  %>
                </td>
              </tr>
              <tr>
                <td></td>
                <td><%= link_to "記事を削除", admins_post_article_path(post_article.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class:"btn btn-danger" %></td>
                <td align="right"><%= post_article.created_at.strftime("%H:%M %Y/%m/%d") %></td>
              </tr>
            </tbody>
          </table>
        <% end %>
      </div>
    <% end %>
  </div>

</div>