config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'questions/index'
    get 'questions/show'
  end
  get 'questions/index'
  get 'questions/show'
  namespace :admins do

  end
  namespace :admins do
    get "/top" => "homes#top", as: "top"

    resources :articles
    resources :categories, only:[:index, :create, :edit, :update]
    resources :users, only:[:index, :show, :update]
    resources :post_articles, only:[:index,:create, :show, :destroy]
    resources :questions, only:[:index, :create, :edit, :update]
    resources :results, only:[:index, :new, :create, :show, :edit, :update]
  end

    devise_for :admins, controllers: {
      sessions: 'admins/sessions'
    }


  scope module: :public do
    devise_for :users

    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :articles, only:[:index, :show]
    resources :users, only:[:show, :edit, :update] do
      resource :relationships, only:[:create, :destroy]
       get 'followings' => 'relationships#followings', as: 'followings'
       get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get :resign
        patch :withdraw
      end
    end
    resources :post_articles, only:[:index, :create, :show, :destroy] do
      resource :favorites, only:[:create, :destroy ]
      resources :post_comments, only:[:create, :destroy]
    end
    resources :questions, only:[:show, :update] do
      collection do
        get :start
        get :goal_1
        get :goal_2
      end
    end
    resources :results, only:[:index, :show]

  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
  belongs_to :category
  
  attachment :image
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :articles
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_article
end

app/models/post_article.rb
class PostArticle < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

  attachment :image

  validates :body, presence: true, length: { minimum: 3 }

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_article
  
  validates :comment, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_articles, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  attachment :profile_image

  validates :name,
      uniqueness: true, length: { in: 2..20 }
  validates :introduction,
      length: { maximum: 100 }

 def follow(user_id)
    relationships.find_or_create_by(followed_id: user_id)
 end
 def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
 end
 def following?(user)
    followings.include?(user)
 end

 def active_for_authentication?
    super && (self.is_active == true)
 end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  
  def top
    @articles = Article.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile_image])
   end
end

app/helpers/admins/articles_helper.rb
module Admins::ArticlesHelper
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/questions_helper.rb
module Admins::QuestionsHelper
end

app/helpers/admins/results_helper.rb
module Admins::ResultsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeBeats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="nav-brand py-2" href="/"><%= image_tag("logo.png") %></a>
          <% if user_signed_in? %>
            <div class="name-box ml-5">
              <p>いらっしゃいませ！　<%= current_user.name %>さん</p>
            </div>
          <% end %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">

              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                  <li>
                    <%= link_to "Mypage", user_path(current_user), class:"nav-link" %>
                  </li>
                  <li>
                    <%= link_to "Leaning", articles_path, class:"nav-link" %>
                  </li>
                  <li>
                    <%= link_to "Communicate(会員制）", post_articles_path, class:"nav-link" %>
                  </li>
                  <li>
                    <%= link_to "Opinion", start_questions_path, class:"nav-link" %>
                  </li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>

                <% elsif admin_signed_in? %>
                  <li>
                    <%= link_to "Users", admins_users_path, class:"nav-link" %>
                  </li>
                  <li>
                    <%= link_to "Leaning", admins_top_path, class:"nav-link" %>
                  </li>
                  <li>
                    <%= link_to "Communicate", admins_post_articles_path, class:"nav-link" %>
                  </li>
                  <li>
                    <%= link_to "Opinion", admins_questions_path, class:"nav-link" %>
                  </li>
                  <%= link_to "Logout", destroy_admin_session_path, method: :delete, class:"nav-link" %>
                <% else %>
                  <%= link_to "About", about_path, class:"nav-link" %>
                  <%= link_to "Signup", new_user_registration_path, class:"nav-link" %>
                  <%= link_to "Login", new_user_session_path, class:"nav-link" %>
                <% end %>
              </ul>
            </div>
        </div>
      </nav>
    </header>

    <main>
    <%= yield %>
    </main>

    <footer>
      <div class="container">
        <div class="row mt-5">
          <p class="mx-auto">CopyRight Chie035</p>
        </div>
      </div>
    </footer>
  </body>
</html>